stages:
  - linting
  - testing
  - running


flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/lints.txt
    - flake8 .

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --diff --check .

pytest:
  stage: testing
  image: python:3.10
  script:
    - pip install -r requirements/test.txt
    - pip install -r requirements/prod.txt
    - cd lyceum
    - python manage.py makemigrations --check --dry-run
    - python manage.py migrate
    - python manage.py loaddata fixtures/data.json
    - python manage.py test
