# Generated by Django 4.2.7 on 2023-11-06 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "feedback_models",
                "verbose_name_plural": "feedbacks_models",
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                default="Привет", max_length=1478, verbose_name="name_models"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("R", "получено"),
                    ("P", "в обработке"),
                    ("A", "ответ дан"),
                ],
                default="R",
                max_length=1,
                verbose_name="status_feedback_models",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name="created_at_utc_models",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="mail",
            field=models.EmailField(
                max_length=254, verbose_name="mail_models"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(verbose_name="text_models"),
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "From",
                    models.CharField(
                        choices=[
                            ("R", "получено"),
                            ("P", "в обработке"),
                            ("A", "ответ дан"),
                        ],
                        editable=False,
                        max_length=1,
                        verbose_name="из статуса",
                    ),
                ),
                (
                    "To",
                    models.CharField(
                        choices=[
                            ("R", "получено"),
                            ("P", "в обработке"),
                            ("A", "ответ дан"),
                        ],
                        editable=False,
                        max_length=1,
                        verbose_name="в статус",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.feedback",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "status_log_models",
                "verbose_name_plural": "status_logs_models",
            },
        ),
    ]
