# Generated by Django 4.2.6 on 2023-10-30 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите категорию(необязательно)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item",
                related_query_name="category",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
    ]
