# Generated by Django 4.2.7 on 2023-11-14 14:20

from django.db import migrations
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0013_alter_user_email"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", users.models.ProfileManager()),
            ],
        ),
    ]
