# Generated by Django 4.2.7 on 2023-11-13 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_alter_profile_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profile",
            managers=[],
        ),
    ]
