# Generated by Django 4.2.7 on 2023-11-15 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_auth_attemps"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="auth_attemps",
            new_name="attempts_count",
        ),
    ]
