# Generated by Django 4.2.6 on 2023-10-29 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_item_is_on_main"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("name", "id"),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
