# Generated by Django 4.2.6 on 2023-10-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите категорию(необязательно)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_query_name="category",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите теги(необязательно)",
                related_query_name="tag",
                to="catalog.tag",
                verbose_name="теги",
            ),
        ),
        migrations.AlterField(
            model_name="itemimages",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                related_query_name="images",
                to="catalog.item",
                verbose_name="товар",
            ),
        ),
    ]
