# Generated by Django 4.2.6 on 2023-10-31 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="дата создания (UTC)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="дата последнего изменения (UTC)"
            ),
        ),
    ]
