# Generated by Django 4.2.6 on 2023-11-02 19:28

import catalog.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_item_created_at_alter_item_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                help_text="Не больше 150 символов",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                help_text="Не больше 150 символов",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="name_en",
            field=models.CharField(
                help_text="Не больше 150 символов",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="name_ru",
            field=models.CharField(
                help_text="Не больше 150 символов",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="text_en",
            field=tinymce.models.HTMLField(
                help_text='Описание должно содержать слово "превосходно" или "роскошно"',
                null=True,
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="текст",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="text_ru",
            field=tinymce.models.HTMLField(
                help_text='Описание должно содержать слово "превосходно" или "роскошно"',
                null=True,
                validators=[
                    catalog.validators.ValidateMustContain(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="текст",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(
                help_text="Не больше 150 символов",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_ru",
            field=models.CharField(
                help_text="Не больше 150 символов",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="название",
            ),
        ),
    ]
