# Generated by Django 4.2.7 on 2023-11-17 15:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="attempts_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                editable=False,
                verbose_name="количество попыток входа",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="blocked_timestamp",
            field=models.DateTimeField(
                null=True, verbose_name="время последней блокировки"
            ),
        ),
    ]
