# Generated by Django 4.2 on 2023-11-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0010_alter_category_options_alter_item_options_and_more"),
        (
            "users",
            "0003_delete_customuser_user_profile_attempts_count_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Ненависть"),
                            (2, "Неприязнь"),
                            (3, "Нейтрально"),
                            (4, "Обожание"),
                            (5, "Любовь"),
                        ],
                        verbose_name="оценка",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="ваш отзыв о товаре",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="created_at_utc_models",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        related_query_name="ratings",
                        to="catalog.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        related_query_name="ratings",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "unique_together": {("user", "item")},
            },
        ),
    ]
